name: Build Hello World application

on:
  push:
    branches:
      - dev
    
jobs:
  prepare-crazy-tools:
    runs-on: ubuntu-latest
    steps:
      - name: configuring some crazy stuff on Node
        uses: actions/setup-node@v3.4.1
  
  run-awesome-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run script
      run: |
         chmod +x ./script.sh
         ./script.sh
      shell: bash
    
  
  
        
