name: Build and deploy Hello World application

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    
jobs:
  checkout-crazy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
  prepare-crazy-tools:
    runs-on: ubuntu-latest
    steps:
      - name: configuring some crazy stuff on Node
        uses: actions/setup-node@v3.4.1
  
  check-crazy-variables:
    runs-on: ubuntu-latest
    steps:
     - run: .github/crazy_variables.sh
    
  
  
        
      
      
